---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    network_mode: host
    restart: always
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: "2000"
      KAFKA_OPTS: 
        -Djava.security.auth.login.config=/etc/zookeeper/zookeeper_jaas.conf 
        -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    extra_hosts:
      - "moby:127.0.0.1"
    volumes:
      - /home/kevinlee/Data/Fortinet/Projects/cp-docker-images/fortinet/multimachinecluster_sasl/conf/zookeeper_jaas.conf:/etc/zookeeper/zookeeper_jaas.conf

  kafka:
    image: confluentinc/cp-enterprise-kafka:latest
    hostname: kafka1
    restart: always
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.100.1:22181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_HOST:SASL_PLAINTEXT
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://192.168.100.1:9092,SASL_PLAINTEXT_HOST://192.168.100.1:29092
      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/broker_jaas.conf
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 192.168.100.1:22181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: PLAIN
      CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SASL_PLAINTEXT
    extra_hosts:
      - "moby:127.0.0.1"
    volumes:
      - /home/kevinlee/Data/Fortinet/Projects/cp-docker-images/fortinet/multimachinecluster_sasl/conf/broker_jaas.conf:/etc/kafka/broker_jaas.conf

  schema_registry:
    image: confluentinc/cp-schema-registry:latest
    restart: always
    hostname: schema_registry
    depends_on:
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "192.168.100.1:22181"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "SASL_PLAINTEXT://192.168.100.1:9092,SASL_PLAINTEXT://192.168.100.10:9093,SASL_PLAINTEXT://192.168.100.11:9094"
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://192.168.100.1:9092,PLAINTEXT://192.168.100.10:9093,PLAINTEXT://192.168.100.11:9094"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
#      SCHEMA_REGISTRY_OPTS:
#        -Djava.security.auth.login.config=/etc/schema_registry/kafka_client_jaas.conf
      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/schema_registry/kafka_client_jaas.conf
    volumes:
      - /home/kevinlee/Data/Fortinet/Projects/cp-docker-images/fortinet/multimachinecluster_sasl/conf/kafka_client_jaas.conf:/etc/schema_registry/kafka_client_jaas.conf

  connect:
    image: confluentinc/cp-kafka-connect:latest
    restart: always
    hostname: connect
    depends_on:
      - zookeeper
      - kafka
      - schema_registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: '192.168.100.1:9092,192.168.100.10:9093,192.168.100.11:9094'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_ZOOKEEPER_CONNECT: 192.168.100.1:22181
      CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: PLAIN
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/kafka_client_jaas.conf
      CONNECT_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/kafka_client_jaas.conf
    volumes:
      - /home/kevinlee/Data/Fortinet/Projects/cp-docker-images/fortinet/multimachinecluster_sasl/conf/kafka_client_jaas.conf:/etc/kafka/kafka_client_jaas.conf

