---
version: '2'
services:
  kafka:
    image: confluentinc/cp-enterprise-kafka:latest
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
      - "19092:19092"
      - "%PORT%:%PORT%"
    environment:
      KAFKA_BROKER_ID: %ID%
      KAFKA_ZOOKEEPER_CONNECT: 192.168.100.1:22181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://%IP%:9092,INTERNAL://%IP%:19092,EXTERNAL://172.30.176.117:%PORT% 
      KAFKA_OPTS:
        -Djava.security.auth.login.config=/etc/kafka/broker_jaas.conf
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: %IP%:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: 192.168.100.1:22181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: "false"
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: PLAIN
      CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SASL_PLAINTEXT
    extra_hosts:
      - "moby:127.0.0.1"
    volumes:
      - %ROOT%/conf/broker_jaas.conf:/etc/kafka/broker_jaas.conf

